/*
# [FIX] Corregir Clave Foránea en sucursal_personal
Corrige el tipo de dato de la columna `sucursal_id` en la tabla `sucursal_personal` para que coincida con el tipo `uuid` de la tabla `sucursales`.

## Query Description:
Esta operación eliminará y volverá a crear la tabla `sucursal_personal`. Si la tabla se creó parcialmente en el intento anterior, se limpiará. No debería haber pérdida de datos ya que la tabla anterior era incorrecta y no se podía utilizar.

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "Medium"
- Requires-Backup: false
- Reversible: false

## Structure Details:
- Modifies: `public.sucursal_personal`
  - Drops the table if it exists.
  - Re-creates the table with the correct `sucursal_id` column type (`uuid`).
  - Re-applies the necessary Row Level Security policies.

## Security Implications:
- RLS Status: Enabled
- Policy Changes: Yes (re-applies correct policies)
- Auth Requirements: Admin to run migration.

## Performance Impact:
- Indexes: Re-creates primary key index.
- Triggers: None.
- Estimated Impact: Low.
*/

-- Eliminar la tabla existente para asegurar una instalación limpia
drop table if exists public.sucursal_personal cascade;

-- Crear la nueva tabla para el personal de la sucursal con el tipo de dato corregido
create table public.sucursal_personal (
  id bigint generated by default as identity primary key,
  sucursal_id uuid not null references public.sucursales(id) on delete cascade,
  nombre text not null,
  estado text not null default 'activo'::text,
  created_at timestamptz not null default now()
);

-- Habilitar la seguridad a nivel de fila (RLS)
alter table public.sucursal_personal enable row level security;

-- Política para permitir a los administradores gestionar todo el personal
create policy "Los administradores pueden gestionar todo el personal."
  on public.sucursal_personal for all
  using ( (select get_user_role(auth.uid())) = 'admin' )
  with check ( (select get_user_role(auth.uid())) = 'admin' );

-- Política para permitir a los usuarios autenticados ver el personal
create policy "Los usuarios autenticados pueden ver el personal."
  on public.sucursal_personal for select
  using ( auth.role() = 'authenticated' );
