-- 1. Create Table: documentos
CREATE TABLE public.documentos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nombre text not null,
  tipo text,
  cliente text,
  sucursal text,
  monto numeric,
  fecha date,
  numero text,
  tamaño_bytes bigint,
  url text not null,
  user_id uuid references auth.users(id) default auth.uid()
);

-- 2. Enable RLS
ALTER TABLE public.documentos ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies
CREATE POLICY "Los administradores pueden gestionar todos los documentos"
ON public.documentos
FOR ALL
TO authenticated
USING (get_user_role(auth.uid()) = 'admin')
WITH CHECK (get_user_role(auth.uid()) = 'admin');

CREATE POLICY "Los usuarios pueden ver todos los documentos"
ON public.documentos
FOR SELECT
TO authenticated
USING (true);

-- 4. Grant usage on the sequence
GRANT USAGE, SELECT ON SEQUENCE documentos_id_seq TO authenticated;
