-- 1. Drop existing objects to ensure a clean slate
-- This will remove the old table linking personnel to system users.
DROP TABLE IF EXISTS public.sucursal_personal CASCADE;
DROP FUNCTION IF EXISTS public.count_personal_by_sucursal();

-- 2. Create the new sucursal_personal table
-- This table stores names directly, without linking to the users table.
CREATE TABLE public.sucursal_personal (
    id bigint generated by default as identity primary key,
    sucursal_id bigint not null references public.sucursales(id) on delete cascade,
    nombre text not null,
    estado text not null default 'activo',
    created_at timestamptz not null default now()
);

-- Comment on new table
COMMENT ON TABLE public.sucursal_personal IS 'Stores personnel names associated with a branch, independent of system users.';

-- 3. Enable Row Level Security
ALTER TABLE public.sucursal_personal ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies for the new table
CREATE POLICY "Authenticated users can view branch personnel"
ON public.sucursal_personal FOR SELECT
USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can manage branch personnel"
ON public.sucursal_personal FOR ALL
USING (get_user_role(auth.uid()) = 'admin')
WITH CHECK (get_user_role(auth.uid()) = 'admin');

-- 5. Recreate the count function to work with the new table
CREATE OR REPLACE FUNCTION public.count_personal_by_sucursal()
RETURNS TABLE(sucursal_id bigint, total_count bigint, active_count bigint)
LANGUAGE sql
AS $$
    SELECT
        s.id as sucursal_id,
        count(sp.id) as total_count,
        count(sp.id) filter (where sp.estado = 'activo') as active_count
    FROM
        public.sucursales s
    LEFT JOIN
        public.sucursal_personal sp ON s.id = sp.sucursal_id
    GROUP BY
        s.id;
$$;
